### ISSUE TITLE
Fix "donate" button

### ISSUE THREAD

**Issue by sursly** [ithacagenerator/WordpressTheme#11]
On this page (and others? There's a comment that a woman couldn't pay for the woodworking course) - http://ithacagenerator.org/support-ithaca-generator/

**Comment by starsplatter** [comment]
I think we resolved this a while ago.

**Comment by sursly** [comment]
Huh, last night when I clicked it I was just taken to the paypal home page, but now it is working great! Sorry.

T

**Comment by starsplatter** [comment]
hrm. Okay, well I guess we'll keep an eye on it. @vicatcu is the best for paypal info.
