### ISSUE TITLE
third level menu items are off the screen

### ISSUE THREAD

**Issue by starsplatter** [ithacagenerator/WordpressTheme#7]
<img width="1280" alt="screen shot 2015-09-11 at 5 28 46 pm" src="https://cloud.githubusercontent.com/assets/2148239/9826749/940d59d4-58aa-11e5-8268-8e7bf132bcbd.png">

**Comment by sursly** [comment]
Good catch! I didn't have submenus in my submenus, locally. I've simply hidden them from showing for now, until we can come up with a better structure (in my opinion/experience, sub submenus are okay for organization, but kind of a pain for interface/navigability).

**Comment by starsplatter** [comment]
Sounds good. I will flatten the structure.
